version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bagisto_app
    restart: always
    volumes:
      - .:/var/www
    networks:
      - bagisto

  nginx:
    image: nginx:alpine
    container_name: bagisto_nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - bagisto

  mysql:
    image: mysql:8.0
    container_name: bagisto_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bagisto
      MYSQL_USER: juan
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bagisto

networks:
  bagisto:

volumes:
  mysql_data:
